const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push('');
lines.push("import { useState } from 'react'");
lines.push("import { useRouter } from 'next/navigation'");
fs.writeFileSync('src/app/(store)/checkout/page.tsx', lines.join('\n'));
lines.push("import Image from 'next/image'");
lines.push("import Link from 'next/link'");
lines.push("import { Button } from '@/components/ui/button'");
lines.push("import { Input } from '@/components/ui/input'");
lines.push("import { Label } from '@/components/ui/label'");
lines.push("import { Textarea } from '@/components/ui/textarea'");
lines.push("import { useCartStore } from '@/stores/cart-store'");
lines.push("import { useAuth } from '@/hooks/use-auth'");
lines.push("import { createClient } from '@/lib/supabase/client'");
lines.push("import { toast } from 'sonner'");
lines.push("import { ShoppingBag, Loader2 } from 'lucide-react'");
lines.push('');
lines.push("const STATES = [");
lines.push("  'Andhra Pradesh',");
